[package]
name = "flappy_game"
version = "1.0.2"
authors = ["satyam"]

[addresses]
flappy_game = "0xe7d3a8337a3bf682022da10fdfca180727436c7787b11d1166a1e78d050bdf38"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
